<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use App\Currency;

class CurrencyTableSeeder extends Seeder{

public function run(){
	$record = [
		
		['name' =>'US Dollar','code' =>'USD','symbol'=>'$','base_usd_amount'=>1.00],
		['name' =>'Canadian Dollar','code'=>'CAD','symbol'=>'CA$','base_usd_amount'=>1.36],
		['name' =>'Euro','code'=>'EUR','symbol'=>'€','base_usd_amount' =>0.91],
		['name' =>'United Arab Emirates Dirham','code'=>'AED','symbol'=>'AED','base_usd_amount'=>3.67],
		['name' =>'Afghan Afghani','code' => 'AFN',  'symbol' => 'Af','base_usd_amount' =>67.66],
		['name' =>'Albanian Lek','code' => 'ALL',  'symbol' => 'ALL','base_usd_amount' =>122.74],
		['name' =>'Armenian Dram','code' => 'AMD',  'symbol' => 'AMD','base_usd_amount' =>482.49],
		['name' =>'Argentine Peso','code' => 'ARS',  'symbol' => 'AR$','base_usd_amount' =>15.35],
		['name' =>'Australian Dollar','code' => 'AUD',  'symbol' => 'AU$','base_usd_amount' =>1.35],
		['name' =>'Azerbaijani Manat','code' => 'AZN',  'symbol' => 'man.','base_usd_amount' =>1.68],
		['name' =>'Bosnia-Herzegovina Convertible Mark','code' => 'BAM',  'symbol' => 'KM','base_usd_amount'=>1.78],
		['name' =>'Bangladeshi Taka','code' => 'BDT',  'symbol' => 'Tk','base_usd_amount' => 81.30],
		['name' =>'Bulgarian Lev','code' => 'BGN',  'symbol' => 'BGN','base_usd_amount' => 1.78],
		['name' =>'Bahraini Dinar','code' => 'BHD',  'symbol' => 'BD','base_usd_amount' => 0.38],
		['name' =>'Burundian Franc','code' => 'BIF',  'symbol' => 'FBu','base_usd_amount' =>1711.00],
		['name' =>'Brunei Dollar','code' => 'BND',  'symbol' => 'BN$','base_usd_amount' =>1.40],
		['name' =>'Bolivian Boliviano','code' => 'BOB',  'symbol' => 'Bs','base_usd_amount' =>6.92],
		['name' =>'Brazilian Real','code' => 'BRL',  'symbol' => 'R$','base_usd_amount' =>3.18],
		['name' =>'Botswanan Pula','code' => 'BWP',  'symbol' => 'BWP','base_usd_amount' =>10.47],
		['name' =>'Belarusian Ruble','code' => 'BYR', 'symbol' => 'BYR','base_usd_amount' =>0026.25],
		['name' =>'Belize Dollar','code' => 'BZD',  'symbol' => 'BZ$  ','base_usd_amount' =>2.01],
		['name' =>'Congolese Franc','code' => 'CDF',  'symbol' => 'CDF  ','base_usd_amount' =>1405.00],
		['name' =>'Swiss Franc','code' => 'CHF',  'symbol' => 'CHF  ','base_usd_amount' =>   0.99],
		['name' =>'Chilean Peso','code' => 'CLP',  'symbol' => 'CL$  ','base_usd_amount' => 671.40],
		['name' =>'Chinese Yuan','code' => 'CNY',  'symbol' => 'CN¥  ','base_usd_amount' =>   6.90],
		['name' =>'Colombian Peso','code' => 'COP',  'symbol' => 'CO$  ','base_usd_amount' =>2971.65],
		['name' =>'Costa Rican Colón','code' => 'CRC',  'symbol' => '₡    ','base_usd_amount' => 557.93],
		['name' =>'Cape Verdean Escudo','code' => 'CVE',  'symbol' => 'CV$','base_usd_amount' => 100.62],
		['name' =>'Czech Republic Koruna','code' => 'CZK',  'symbol' => 'Kč','base_usd_amount' =>  24.32],
		['name' =>'Djiboutian Franc','code' => 'DJF',  'symbol' =>'Fdj','base_usd_amount' => 178.78],
		['name' =>'Danish Krone','code' => 'DKK',  'symbol' => 'Dkr','base_usd_amount' =>   6.76],
		['name' =>'Dominican Peso','code' => 'DOP',  'symbol' => 'RD$','base_usd_amount' =>  47.09],
		['name' =>'Algerian Dinar','code' => 'DZD',  'symbol' => 'DA','base_usd_amount' => 109.30],
		['name' =>'Estonian Kroon','code' => 'EEK',  'symbol' => 'Ekr','base_usd_amount' =>   NULL],
		['name' =>'Egyptian Pound','code' => 'EGP',  'symbol' => 'EGP','base_usd_amount' =>  18.08],
		['name' =>'Eritrean Nakfa','code' => 'ERN',  'symbol' => 'Nfk','base_usd_amount' =>  15.33],
		['name' =>'Ethiopian Birr','code' => 'ETB',  'symbol' => 'Br','base_usd_amount' =>  23.06],
		['name' =>'British Pound Sterling','code' => 'GBP',  'symbol' => '£','base_usd_amount'=> 0.77],
		['name' =>'Georgian Lari','code' => 'GEL',  'symbol' => 'GEL','base_usd_amount' =>   2.44],
		['name' =>'Ghanaian Cedi','code' => 'GHS',  'symbol' => 'GH₵','base_usd_amount' =>   4.18],
		['name' =>'Guinean Franc','code' => 'GNF',  'symbol' => 'FG','base_usd_amount' =>9125.00],
		['name' =>'Guatemalan Quetzal','code' => 'GTQ',  'symbol' => 'GTQ','base_usd_amount' =>   7.32],
		['name' =>'Hong Kong Dollar','code' => 'HKD',  'symbol' => 'HK$','base_usd_amount' =>   7.78],
		['name' =>'Honduran Lempira','code' => 'HNL', 'symbol' => 'HNL','base_usd_amount' =>  23.46],
		['name' =>'Croatian Kuna','code' => 'HRK',  'symbol' => 'kn','base_usd_amount' =>   6.75],
		['name' =>'Hungarian Forint','code' => 'HUF',  'symbol' => 'Ft','base_usd_amount' => 283.40],
		['name' =>'Indonesian Rupiah','code' => 'IDR',  'symbol' => 'Rp','base_usd_amount' =>3329.28],
		['name' =>'Israeli New Sheqel','code' => 'ILS',  'symbol' => '₪','base_usd_amount' =>   3.59],
		['name' =>'Indian Rupee','code' => 'INR',  'symbol' => 'Rs','base_usd_amount' =>  64.32],
		['name' =>'Iraqi Dinar','code' => 'IQD',  'symbol' => 'IQD ','base_usd_amount' =>1182.00],
		['name' =>'Iranian Rial','code' => 'IRR',  'symbol' => 'IRR','base_usd_amount' =>2454.63],
		['name' =>'Icelandic Króna','code' => 'ISK',  'symbol' => 'Ikr','base_usd_amount' => 105.58],
		['name' =>'Jamaican Dollar','code' => 'JMD',  'symbol' => 'J$','base_usd_amount' => 128.75],
		['name' =>'Jordanian Dinar','code' => 'JOD',  'symbol' => 'JD','base_usd_amount' =>   0.71],
		['name' =>'Japanese Yen','code' => 'JPY',  'symbol' => '¥','base_usd_amount' => 112.73],
		['name' =>'Kenyan Shilling','code' => 'KES',  'symbol' => 'Ksh','base_usd_amount' => 103.11],
		['name' =>'Cambodian Riel','code' => 'KHR',  'symbol' => 'KHR','base_usd_amount' =>4031.00],
		['name' =>'Comorian Franc','code' => 'KMF',  'symbol' => 'CF','base_usd_amount' => 448.23],
		['name' =>'South Korean Won','code' => 'KRW',  'symbol' => '₩','base_usd_amount' =>1135.73],
		['name' =>'Kuwaiti Dinar','code' => 'KWD',  'symbol' => 'KD','base_usd_amount' =>   0.30],
		['name' =>'Kazakhstani Tenge','code' => 'KZT',  'symbol' => 'KZT','base_usd_amount' => 317.12],
		['name' =>'Lebanese Pound','code' => 'LBP',  'symbol' => 'LB£  ','base_usd_amount' =>1512.50],
		['name' =>'Sri Lankan Rupee','code' => 'LKR',  'symbol' => 'SLRs','base_usd_amount' => 151.81],
		['name' =>'Lithuanian Litas','code' => 'LTL',  'symbol' => 'Lt','base_usd_amount' =>   NULL],
		['name' =>'Latvian Lats','code' => 'LVL',  'symbol' => 'Ls','base_usd_amount' =>   NULL],
		['name' =>'Libyan Dinar','code' => 'LYD',  'symbol' => 'LD','base_usd_amount' =>   1.41],
		['name' =>'Moroccan Dirham','code' => 'MAD',  'symbol' => 'MAD','base_usd_amount' =>   9.85],
		['name' =>'Moldovan Leu','code' => 'MDL',  'symbol' => 'MDL','base_usd_amount' =>  18.82],
		['name' =>'Malagasy Ariary','code' => 'MGA',  'symbol' => 'MGA','base_usd_amount' =>3195.00],
		['name' =>'Macedonian Denar','code' => 'MKD',  'symbol' => 'MKD','base_usd_amount' =>  56.10],
		['name' =>'Myanma Kyat','code' => 'MMK',  'symbol' => 'MMK','base_usd_amount' =>1354.80],
		['name' =>'Macanese Pataca','code' => 'MOP',  'symbol' => 'MOP$','base_usd_amount' =>   8.02],
		['name' =>'Mauritian Rupee','code' => 'MUR',  'symbol' => 'MURs','base_usd_amount' =>  34.55],
		['name' =>'Mexican Peso','code' => 'MXN',  'symbol' => 'MX$','base_usd_amount' =>  19.00],
		['name' =>'Malaysian Ringgit','code' => 'MYR',  'symbol' => 'RM','base_usd_amount' =>   4.34],
		['name' =>'Mozambican Metical','code' => 'MZN',  'symbol' => 'MTn','base_usd_amount' =>  64.00],
		['name' =>'Namibian Dollar','code' => 'NAD',  'symbol' => 'N$','base_usd_amount' =>  13.52],
		['name' =>'Nigerian Naira','code' => 'NGN',  'symbol' => '₦','base_usd_amount' => 313.58],
		['name' =>'Nicaraguan Córdoba','code' => 'NIO','symbol' => 'C$','base_usd_amount' =>  29.80],
		['name' =>'Norwegian Krone','code' => 'NOK',  'symbol' => 'Nkr','base_usd_amount' =>   8.59],
		['name' =>'Nepalese Rupee','code' => 'NPR',  'symbol' => 'NPRs','base_usd_amount' => 102.58],
		['name' =>'New Zealand Dollar','code' => 'NZD',  'symbol' => 'NZ$','base_usd_amount' =>   1.45],
		['name' =>'Omani Rial','code' => 'OMR',  'symbol' => 'OMR  ','base_usd_amount' =>   0.38],
		['name' =>'Panamanian Balboa','code' => 'PAB',  'symbol' => 'B/.','base_usd_amount' =>   1.00],
		['name' =>'Peruvian Nuevo Sol','code' => 'PEN',  'symbol' => 'S/.','base_usd_amount' =>   3.27],
		['name' =>'Philippine Peso','code' => 'PHP',  'symbol' => '₱','base_usd_amount' =>  49.84],
		['name' =>'Pakistani Rupee','code' => 'PKR',  'symbol' => 'PKRs','base_usd_amount' => 104.75],
		['name' =>'Polish Zloty','code' => 'PLN',  'symbol' => 'zł','base_usd_amount' =>   3.83],
		['name' =>'Paraguayan Guarani','code' => 'PYG',  'symbol' => '₲','base_usd_amount' =>5664.90],
		['name' =>'Qatari Rial','code' => 'QAR',  'symbol' => 'QR','base_usd_amount' =>   3.64],
		['name' =>'Romanian Leu','code' => 'RON',  'symbol' => 'RON','base_usd_amount' =>   4.14],
		['name' =>'Serbian Dinar','code' => 'RSD',  'symbol' => 'din.','base_usd_amount' => 111.85],
		['name' =>'Russian Ruble','code' => 'RUB',  'symbol' => 'RUB','base_usd_amount' =>  58.06],
		['name' =>'Rwandan Franc','code' => 'RWF',  'symbol' => 'RWF','base_usd_amount' => 836.95],
		['name' =>'Saudi Riyal','code' => 'SAR',  'symbol' => 'SR   ','base_usd_amount' =>   3.75],
		['name' =>'Sudanese Pound','code' => 'SDG',  'symbol' => 'SDG','base_usd_amount' =>   6.68],
		['name' =>'Swedish Krona','code' => 'SEK',  'symbol' => 'Skr','base_usd_amount' =>   8.79],
		['name' =>'Singapore Dollar','code' => 'SGD',  'symbol' => 'S$','base_usd_amount' =>   1.40],
		['name' =>'Somali Shilling','code' => 'SOS',  'symbol' => 'Ssh','base_usd_amount' => 576.81],
		['name' =>'Syrian Pound','code' => 'SYP',  'symbol' => 'SY£','base_usd_amount' => 214.40],
		['name' =>'Thai Baht','code' => 'THB',  'symbol' => '฿','base_usd_amount' =>  34.65],
		['name' =>'Tunisian Dinar','code' => 'TND',  'symbol' => 'DT','base_usd_amount' =>   2.41],
		['name' =>'Tongan Paʻanga','code' => 'TOP',  'symbol' => 'T$','base_usd_amount' =>   2.35],
		['name' =>'Turkish Lira','code' => 'TRY',  'symbol' => 'TL','base_usd_amount' =>   3.54],
		['name' =>'Trinidad and Tobago Dollar','code' => 'TTD',  'symbol' => 'TT$','base_usd_amount' =>   6.71],
		['name' =>'New Taiwan Dollar','code' => 'TWD',  'symbol' => 'NT$','base_usd_amount' =>  30.18],
		['name' =>'Tanzanian Shilling','code' => 'TZS',  'symbol' => 'TSh','base_usd_amount' =>2234.40],
		['name' =>'Ukrainian Hryvnia','code' => 'UAH',  'symbol' => '₴','base_usd_amount' =>  26.40],
		['name' =>'Ugandan Shilling','code' => 'UGX',  'symbol' => 'USh','base_usd_amount' =>3614.60],
		['name' =>'Uruguayan Peso','code' => 'UYU',  'symbol' => '$U','base_usd_amount' =>  27.84],
		['name' =>'Uzbekistan Som','code' => 'UZS',  'symbol' => 'UZS','base_usd_amount' =>3721.25],
		['name' =>'Venezuelan Bolívar','code' => 'VEF',  'symbol' => 'Bs.F.','base_usd_amount' =>  10.11],
		['name' =>'Vietnamese Dong','code' => 'VND',  'symbol' => '₫','base_usd_amount' =>2711.92],
		['name' =>'CFA Franc BEAC','code' => 'XAF',  'symbol' => 'FCFA','base_usd_amount' => 597.10],
		['name' =>'CFA Franc BCEAO','code' => 'XOF',  'symbol' => 'CFA','base_usd_amount' => 597.15],
		['name' =>'Yemeni Rial','code' => 'YER',  'symbol' => 'YR','base_usd_amount' => 250.30],
		['name' =>'South African Rand','code' => 'ZAR',  'symbol' => 'R','base_usd_amount' =>  13.41],
		['name' =>'Zambian Kwacha','code' => 'ZMK',  'symbol' => 'ZK','base_usd_amount' =>5252.02],

	];
		foreach ($record as $key => $value) {
			$value['created_at'] = date('Y-m-d h:i:s');
			$value['updated_at'] = date('Y-m-d h:i:s');
			DB::table('currency')->insert($value);
		}

	}

}